# Almost entirely based on this Microsoft guide: https://learn.microsoft.com/en-us/azure/developer/ansible/vm-configure-windows?tabs=ansible 
- name: Create RHEL test vm
  hosts: localhost
  connection: local
  gather_facts: false 

  tasks:
  - name: Create resource group
    azure.azcollection.azure_rm_resourcegroup:
      name: "{{ resource_group }}"
      location: eastus

  - name: Create virtual network
    azure.azcollection.azure_rm_virtualnetwork:
      resource_group: "{{ resource_group }}"
      name: "{{ virtual_network }}"
      address_prefixes: "10.0.0.0/16"

  - name: Add subnet
    azure.azcollection.azure_rm_subnet:
      resource_group: "{{ resource_group }}"
      name: "{{ subnet }}"
      address_prefix: "10.0.1.0/24"
      virtual_network: "{{ virtual_network }}"

  - name: Create public IP address for ansible-test-vm
    azure.azcollection.azure_rm_publicipaddress:
      resource_group: "{{ resource_group }}"
      allocation_method: Static
      name: ansible-public-ip
    register: output_ip_address

  - name: Public IP of VM
    debug:
      msg: "The public IP for ansible-test-vm is {{ output_ip_address.state.ip_address }}."

  - name: Create Network Security Group that allows SSH
    azure.azcollection.azure_rm_securitygroup:
      resource_group: "{{ resource_group }}"
      name: "{{ security_group }}"
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound

  - name: Create virtual network interface card
    azure.azcollection.azure_rm_networkinterface:
      resource_group: "{{ resource_group }}"
      name: myNIC
      virtual_network: "{{ virtual_network }}"
      subnet: "{{ subnet }}"
      ip_configurations:
        - public_ip_name: ansible-public-ip
          name: myAnsibleIPConf
      security_group: "{{ security_group }}"

  - name: Create ansible-test-vm
    azure.azcollection.azure_rm_virtualmachine:
      started: true
      resource_group: "{{ resource_group }}"
      name: ansible-test-rhel-vm
      vm_size: Standard_B1s
      admin_username: azureuser
      ssh_password_enabled: false
      ssh_public_keys:
        - path: /home/azureuser/.ssh/authorized_keys
          key_data: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}" 
      network_interfaces: myNIC
      managed_disk_type: Standard_LRS
      os_disk_size_gb: 100
      image:
        offer: rhel
        publisher: redhat
        sku: 95_gen2
        version: latest
      data_disks:
        - lun: 60
          caching: "ReadOnly"
          disk_size_gb: 50
          managed_disk_type: Standard_LRS
    register: ansible_vm 

  - name: refresh dynamic inventory 
    ansible.builtin.meta: refresh_inventory

- name: Connect and configure additional disk 
  hosts: ansible-test-rhel-vm 
  gather_facts: no 
  become: yes

  tasks:
    - name: Create a new ext4 primary partition
      community.general.parted:
        device: /dev/sdc
        number: 1
        state: present
        fs_type: ext4    

    - name: Create a ext4 filesystem on /dev/sdc1
      community.general.filesystem:
        fstype: ext4
        dev: /dev/sdc1

    # - name: Create  ansible user 
    #   ansible.builtin.user: 
    #     name: ansible 
    #     password: "{{ password | password_hash }}"
    #     groups: wheel 
    #     append: true 

    - name: Create mountpoint for new disk
      ansible.builtin.file:
        path: /ansible 
        state: directory 
        # owner: ansible 
        # group: ansible 

    - name: Mount disk to /ansible
      ansible.posix.mount:
        path: /ansible
        src: /dev/sdc1
        fstype: ext4
        state: mounted

    - name: create ansible user with new home
      ansible.builtin.user: 
        name: ansible 
        password: "{{ password | password_hash }}"
        state: present
        # move_home: true 
        home: /ansible
        groups: wheel 
        append: true

    - name: Set home directory permissions
      ansible.builtin.file:
        path: /ansible 
        state: directory 
        owner: ansible 
        group: ansible 

    - name: setfcontext for the new home directory 
      community.general.sefcontext: 
        target: "/ansible(/.*)?"
        setype: user_home_dir_t
        ftype: "a"
        state: present 

    - name: Run restore context to reload selinux
      shell: restorecon -R "/ansible"

    - name: Enable password authentication 
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config.d/50-cloud-init.conf
        regexp: 'PasswordAuthentication no'
        line: 'PasswordAuthentication yes'

    - name: Reload service sshd
      ansible.builtin.systemd_service:
        name: sshd.service
        state: restarted