--- 
- name: Check for instances that are untagged in ansible-test-rg 
  hosts: localhost 

  tasks:
    - name: Get list of vms in ansible-test-rg 
      azure_rm_virtualmachine_info:
        resource_group: "{{ resource_group }}"
      register: azure_vms 

    - name: List VMs in ansible-test-rg with no tags 
      ansible.builtin.debug:
        msg: 
          - "Virtual Machines with NO tags:"
          - "{{ azure_vms | community.general.json_query('vms[?tags==None].name') }}"  