--- 
- name: Create Azure PostgreSQL Flexible Database 
  hosts: localhost 

  tasks:

    - name: Create resource group
      azure.azcollection.azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: eastus

    - name: Create (or update) PostgreSQL Flexible Server
      azure.azcollection.azure_rm_postgresqlflexibleserver:
        resource_group: "{{ resource_group }}"
        name: aapdbserver
        sku:
          name: Standard_B1ms
          tier: Burstable
        administrator_login: azureuser
        administrator_login_password: "{{ password }}"
        version: 15
        storage:
          storage_size_gb: 40
        #fully_qualified_domain_name: st-private-dns-zone.postgres.database.azure.com
        backup:
          backup_retention_days: 7
          geo_redundant_backup: Disabled
        maintenance_window:
          custom_window: Enabled
          start_hour: 8
          start_minute: 0
          day_of_week: 0
        # point_in_time_utc: 2023-05-31T00:28:17.7279547+00:00
        # availability_zone: 1
        create_mode: Default
      register: flexible_pg_server

    - name: Create AAP Postgresql dbs 
      azure.azcollection.azure_rm_postgresqlflexibledatabase:
        resource_group: "{{ resource_group }}"
        server_name: aapdbserver 
        name: "{{ item }}" 
        charset: UTF8 
        collation: en_US.utf8 
        state: present 
      loop:
        - controller 
        - hub 
        - eda 
        - gateway 

    - name: Get current public IP address for firewall rule 
      ansible.builtin.uri:
        url: https://api.ipify.org?format=json 
      register: public_ip 

    - name: Create (or update) PostgreSQL flexible firewall rule
      azure.azcollection.azure_rm_postgresqlflexiblefirewallrule:
        state: present
        resource_group: "{{ resource_group }}"
        server_name: aapdbserver
        name: home-to-azure-aap-db
        start_ip_address: "{{ public_ip.json.ip }}"
        end_ip_address: "{{ public_ip.json.ip }}" # my current AAP instance IP Address

    - name: Get list of enabled extensions
      azure.azcollection.azure_rm_resource_info:
        provider: DBforPostgreSQL
        resource_group: "{{ resource_group }}"
        resource_name: aapdbserver/configurations/azure.extensions
        resource_type: flexibleServers
        api_version: "2022-12-01"
      register: postgresql_info

    - name: Enable extensions
      azure.azcollection.azure_rm_resource:
        idempotency: true
        provider: DBforPostgreSQL
        resource_group: "{{ resource_group }}"
        resource_name: aapdbserver/configurations/azure.extensions
        resource_type: flexibleServers
        body: "{{ postgresql_info.response[0] |
          combine({'properties': {'value': (infrastructure_database_extensions | default('') | join(',')), 'source': 'user-override'}}) }}"

    - name: Enable hstore extension 
      community.postgresql.postgresql_query:
        db: "{{ item }}"
        query: "CREATE EXTENSION hstore;"
        login_host: aapdbserver.postgres.database.azure.com
        login_user: azureuser
        login_password: "{{ password }}"
      loop:
        - controller 
        - hub 
        - eda 
        - gateway 