---
version: 3

images:
  base_image:
    # name: registry.redhat.io/ansible-automation-platform-25/ee-supported-rhel9@sha256:2a04708a02d2bf5b549bb0da9a1dfe156fd773af41098a77b5cc435b27d88c44
    name: registry.redhat.io/ansible-automation-platform-25/ansible-python-base-rhel9@sha256:109b058d0d367699bcc5ddce27cb820e0f82eb111b51ed768ed67a88ae0880f0
    # name: registry.redhat.io/ansible-automation-platform-25/ansible-python-base-rhel8@sha256:a2b9b4b0087e9d393978c24f7a5ad87a98248f11ea1d822e30420198d264410e
    # name: registry.redhat.io/ansible-automation-platform/ee-minimal-rhel9@sha256:c6617b6b711eeab20b4b31a5259eac58d5244cd8f7b8ccb149847719677ee18f
dependencies:
  ansible_core:
    package_pip: ansible-core==2.17.2
  ansible_runner:
    package_pip: ansible-runner==2.3.6
  galaxy:
    collections:
      - { name: azure.azcollection, version: 3.2.0 }
      - { name: community.general, version: 10.3.0 }
      - { name: community.postgresql, version: 3.10.2 }
      - { name: ansible.posix, version: 1.6.2 }
      - { name: ansible.windows, version: 2.8.0 }

  python:
    - passlib
    - pywinrm>=0.3.0
    - azure-mgmt-compute
    - azure-mgmt-storage
    - azure-mgmt-resource
    - azure-mgmt-resourcehealth
    - azure-keyvault-secrets
    - azure-storage-blob

additional_build_steps:
  prepend_base:
    - RUN $PYCMD -m pip install --upgrade pip setuptools
    - RUN /usr/bin/microdnf install unzip -y

options:
  package_manager_path: /usr/bin/microdnf
  tags:
      - aap.aj.peripatetic.us/azure_ee:2.1