---
version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform/ee-minimal-rhel9@sha256:c6617b6b711eeab20b4b31a5259eac58d5244cd8f7b8ccb149847719677ee18f

dependencies:
  galaxy:
    collections:
      - { name: amazon.aws, version: 9.2.0 }
      - { name: azure.azcollection, version: 3.2.0 }
      - { name: community.aws, version: 9.0.0 }
      - { name: community.general, version: 10.3.0 }
      - { name: kubernetes.core, version: 5.1.0 }
  python:
    - awscli>=1.16.312
  exclude:
    system:
      - openshift-clients
      
options:
  package_manager_path: /usr/bin/microdnf