---
version: 3

images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform/ee-minimal-rhel9@sha256:c6617b6b711eeab20b4b31a5259eac58d5244cd8f7b8ccb149847719677ee18f

dependencies:
  galaxy:
    collections:
      - { name: amazon.aws, version: 9.2.0 }
      - { name: azure.azcollection, version: 3.2.0 }
      - { name: community.aws, version: 9.0.0 }
      - { name: community.general, version: 10.3.0 }
      - { name: community.postgresql, version: 3.10.2 }
      - { name: kubernetes.core, version: 5.1.0 }
      - { name: ansible.posix, version: 1.6.2 }
      - { name: ansible.windows, version: 2.8.0 }
      - { name: cloud.terraform, version: 3.0.0 }
  python:
    - awscli>=1.16.312
    - passlib
    - pywinrm>=0.3.0

  exclude:
    system:
      - openshift-clients

additional_build_steps:
  prepend_base:
    - RUN $PYCMD -m pip install --upgrade pip setuptools
  append_base:
    - RUN curl "https://releases.hashicorp.com/terraform/1.10.4/terraform_1.10.4_linux_amd64.zip" -o "/terraform.zip"
    - RUN unzip /terraform.zip -d /terraform
    - RUN mv /terraform/terraform /bin
    
options:
  package_manager_path: /usr/bin/microdnf
  tags:
      - gateway.sandbox3281.opentlc.com/azure_ee:1.6