--- 
- name: Install Windows Updates
  hosts: all 
  vars:
    ansible_winrm_transport: ntlm
    ansible_connection: winrm
    ansible_port: 5985

  tasks:
    - name: Run updates 
      ansible.windows.win_updates:
        category_names:
          - SecurityUpdates
        reboot: "{{ reboot | default('False') }}"
        reject_list:
          - KB2267602
      become: true
      become_method: runas
      become_user: SYSTEM